package by.avramchuk.fs.controller;

public enum CommandName {
	
	GO_TO_BASE_PAGE, DO_SIGN_IN, DO_SEARCH, DO_REGISTRATION, CONFIRM_REGISTRATION, GO_TO_USER_PROFILE,
	GO_TO_FS_PROJECT, SHOW_USER_INFO, GO_TO_FS_EDITOR, EDIT_PERSONAL_DATA
}
